name: CI
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  ci:
    name: '${{ matrix.os.name}} | Java ${{ matrix.java.version}}'
    runs-on: ${{ matrix.os.id }}
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      matrix:
        os:
          - id: ubuntu-latest
            name: Linux
        java:
          - version: 17
            toolchain: false
          - version: 20
            toolchain: true
    steps:
      - name: Prepare Windows runner
        if: ${{ runner.os == 'Windows' }}
        run: |
          git config --global core.autocrlf true
          git config --global core.longPaths true
          Stop-Service -name Docker
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          publish: true
          java-version: ${{ matrix.java.version }}
          java-early-access: ${{ matrix.java.early-access || 'false' }}
          java-toolchain: ${{ matrix.java.toolchain }}
          develocity-access-key: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jars-${{ matrix.java.version }}-${{ matrix.os.name }}
          path: |
            ./**/*.jar